#pragma once

#include <iostream>

enum Error
{
	NO_INPUT_FILE,
	BASM_NOT_SET,
	INPUT_FILE_NOT_FOUND,
	TOO_MANY_ARGUMENTS,
	COMMAND_NOT_RECOGNIZED,
	OUTPUT_NOT_SET,
	SOURCE_ALREADY_SET,
	OUTPUT_ALREADY_SET,
	MALLOC_ERROR_SRC_SEGMENT,
	MALLOC_ERROR_TEXT_SEGMENT,
	MALLOC_ERROR_DATA_SEGMENT,
	MALLOC_ERROR_STACK_SEGMENT,
	MALLOC_ERROR_SYMBOL_TABLE,
	VM_UNKNOWN_INSTRUCTION,
	SOURCE_READING_ERROR

};

void BengiError(int errorId, char* arg = 0);
void VMError(int errorId, int arg);